### PR TITLE
Plp id loop

### PR DESCRIPTION
**Pull request by DF5EQ**
In Austria PLP ID 1 is used. With only the use of PLP ID 0 in the scan loop no channel is found. In countries.c the PLP ID range can be set for every country.

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
I think you created this branch from a previous feature branch, instead of master, because it includes the commits in the other 2 PRs.

**Comment by DF5EQ** [comment]
Yes, you are right.

Attached a screenshot of my git repository.
May be that I made some mistakes in contributing and submiting the PRs.
It's my first use of Github.

Am 06.10.2018 um 20:24 schrieb Ștefan Talpalaru:

**Comment by stefantalpalaru** [comment]
I'm OK with combining all three pull requests in this one and closing the other two.

**Comment by DF5EQ** [comment]
Wait until I changed the delsys on a per country basis.
I will send a new combined PR.

Am 06.10.2018 um 21:10 schrieb Ștefan Talpalaru:

**Comment by stefantalpalaru** [comment]
Whatever is easier for you.

**Pull request closed without merging**
