### PR TITLE
dvbv5 format export support (including man and help)

### PR DESCRIPTION
**Pull request by jmwislez**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
It's missing a definition for `sat_pol_to_txt_v5()`.

Also, it's OK to keep pushing commits to a single PR branch, instead of closing and creating new PRs. Whatever you push to the "master" branch of your forked repo will appear here, automatically.

**Comment by jmwislez** [comment]
Sorry, I forgot to include one file.  I'm already working on another update (for xml transponder/services dump) and working with pull requests is new to me.

**Comment by stefantalpalaru** [comment]
Don't worry, you'll get the hang of it.

**Comment by stefantalpalaru** [comment]
Merged.

It's easier to create different branches for different PRs, if you're working on multiple PRs in parallel.

**Pull request merged**
